### ISSUE TITLE
Sanitize and format the text in the articles

### ISSUE THREAD

**Issue by mrpozzi** [EST-Team-Adam/TheReadingMachine#5]
Stemming, formatting, ngramming, etc...

**Comment by albertomun** [comment]
I think that stemming is something that helps in classifying the articles because it reduces the feature set of its repetitions (plurals for example). For test purposes I've stemmed a sample of articles and I'm now figuring out which is the best stemmer.
By the way I'll upload the script as soon as possible.

**Comment by mrpozzi** [comment]
@albertomun I have some good packages for doing that up my sleeve, I'll include them in the plan of action which I'll send out this week. 

If you have some time see if you can familiarize yourself with nlkt and in general with CRF/POS tagging models.

**Comment by mkao006** [comment]
There are also duplicated articles which need to be removed.
